### ISSUE TITLE
Image gallery of a house

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#15]
We need to show to user the house's images inside of a gallery.

**Comment by AgonIdrizi** [comment]
Hi ,
I want to contribute to magara.
Just give me some info what to use, carrierwave or active-storage for images.
Thank You.

**Comment by BerkhanBerkdemir** [comment]
Thanks, @AgonIdrizi!

Well, we can do this feature with Active Storage because Active Storage is ready to use for this project, but before that, we need to discuss how it will be (UI or software design).

Could you write some steps about how will you achieve that?

Also, I some design changes available with #58, so we could have conflicted files.

Thanks again :blue_heart:

**Comment by AgonIdrizi** [comment]
Hi @BerkhanBerkdemir ,
I was hoping to implement this https://github.com/blueimp/Gallery, 
check live demo: https://blueimp.github.io/Gallery/
Thanks <3,
Agon.

**Comment by BerkhanBerkdemir** [comment]
It is awesome gallery library and has perfect documentation. Look good to me :+1:, @AgonIdrizi! So, we're going to use Active Storage and Gallery.

**Comment by AgonIdrizi** [comment]
Yes @BerkhanBerkdemir , i will do it, Active Storage and Gallery let it be. Thanks

**Comment by noloman** [comment]
how are we going to store them? using the Disk Service or a third-party such as Google Cloud, Amazon S3, Microsoft Azure, etc?

**Comment by BerkhanBerkdemir** [comment]
We need to see that PR first for what we have, but we can't use Disk on Heroku-like PaaS. However, I think we can provide a setup wizard for administrator which they  will select and configure that storage type.

**Comment by AgonIdrizi** [comment]
Hi @BerkhanBerkdemir ,
Check the gallery.
https://github.com/magara/magara/pull/62

Also we need to change the Edit page, so user can delete photos.Right now there is no option in edit page to delete photos.There is just a option to add more photos. I can do this, will open an issue for it :).
