### ISSUE TITLE
Use trix for description editor

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#24]
[basecamp/trix](https://github.com/basecamp/trix) will be used for the building's description section.

**Comment by jaquesdias** [comment]
Hi @BerkhanBerkdemir, could assign this issue to me? I'll like to work on it. Thanks.

**Comment by BerkhanBerkdemir** [comment]
Thank you, @jaquesdias, but first could you create a PR?

**Comment by jaquesdias** [comment]
Yes sir!
