### ISSUE TITLE
Integration with search engines

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#25]
Searching will be critical component for Mağara because nobody wants to check
every single page to find a house.

I have played with Elasticsearch 5, but it doesn't mean that it is only one in
the world<sup>[1]</sup>, so we should consider other search engine options such
as, Solr, Algolia etc.

## What will we achieve with a search engine?

Yeah, we need to ask before diving into code, right? Well, like I said before
*"searching will be our backbone"*.

* Searching with in the map (latitude and longitude are ready for this). Being
capable to search with advanced features like Checkbox (model), rent or rating
* Analyzing logs to find problems - further versions, not now

## Why Elasticsearch?

I prefer Elasticsearch as a sysadmin or a Rails developer since I can use for
searching houses or logs (with logstash), and also, it provides Kibana, ES
dashboard, to visualize data that we have.

We have different gems in Rails community like:

* [`elasticsearch-rails`][elasticsearch-rails] and `elasticsearch-model`:
  Offical Rails gem to communicate ES API.
* [`chewy`][chewy]: High level framework which is based on `elasticsearch-ruby`
* [`searchkick`][searchkick]: *Batteries included* search solution

[1]: https://db-engines.com/en/ranking/search+engine
[elasticsearch-rails]: https://github.com/elastic/elasticsearch-rails
[chewy]: https://github.com/toptal/chewy
[searchkick]: https://github.com/ankane/searchkick

**Comment by noloman** [comment]
Hi, can I claim this? 
I was planning to create a search functionality so users can look for houses (maybe also addresses?) with ElasticSearch

**Comment by BerkhanBerkdemir** [comment]
Of course, @noloman, but should we implement #44 before this one because with #44, we will add some column that we can use with elasticsearch.
