### ISSUE TITLE
Write RSpec for models and controllers

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#26]
I'm looking contributor who can write RSpec for this project. This project **must** be well tested with RSpec.

**Comment by mathyoudawson** [comment]
I would like to start working on this. Can I submit this in multiple PR's as not to go into a rabbit hole

**Comment by BerkhanBerkdemir** [comment]
Of course, @mathyoudawson. Also, I want to mention that maybe I couldn't answer for 2 days. That's why please mention me when you have a question because I check my emails all the time.

Good luck :smile:

**Comment by BerkhanBerkdemir** [comment]
CI failed on [magara/magara `master`](https://semaphoreci.com/magara/magara/branches/master/builds/2) because of my RSpec. We can rename that RSpec file.

**Comment by BerkhanBerkdemir** [comment]
Is there any update for this issue, @mathyoudawson?

**Comment by mathyoudawson** [comment]
I've started to spec out the model. I've spent the last couple days wrapping my head around the codebase. Hopefully will make a PR later today :)
