### ISSUE TITLE
Deploy to Heroku for staging stage

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#32]
We will use Heroku for staging stage which will allow us to see where are we on `master` branch.

The staging stage will have

* [PostgreSQL](https://elements.heroku.com/addons/heroku-postgresql)
* [Redis](https://elements.heroku.com/addons/heroku-redis)
* [SendGrid](https://elements.heroku.com/addons/sendgrid)

## To do list

- [ ] [Add `Procfile`](https://github.com/magara/magara/projects/1#card-13208831)

**Comment by mathyoudawson** [comment]
Awesome :) 
How often will we release to Heroku?

**Comment by BerkhanBerkdemir** [comment]
When we push the changes to `master`, we will release, @mathyoudawson.
