### ISSUE TITLE
Add developer installation guide for Mac OS

### ISSUE THREAD

**Issue by noloman** [magara/magara#34]
Hi!

I'd like to start contributing to this project, but I don't exactly know how to set up the development environment for Mac OS.

Thanks!

**Comment by mathyoudawson** [comment]
Hi 👋 

Where did you get up to on the installation guide on the Readme? If you have any errors let me know and I can help you out.

**Comment by BerkhanBerkdemir** [comment]
Hey @noloman,

Thank you for your interest. I think, we can store installation guide on our Wiki pages. Could you give us a brief or example of table of contents?

**Comment by noloman** [comment]
I haven't even started, since it is all about Ubuntu.
I have downloaded and installed Docker, but I don't how to set Docker up for this specific project (or for any project since I haven't ever used Docker)

**Comment by BerkhanBerkdemir** [comment]
Docker community has beautiful documentation for [Compose](https://docs.docker.com/compose) and [Docker](https://docs.docker.com/docker-for-mac/install), @noloman.

**Comment by BerkhanBerkdemir** [comment]
@noloman, if you have `docker-compose`, you can run `docker-compose up -d`. It will set PostgreSQL for you. You can follow [this guide](https://github.com/magara/magara/wiki/Developer-Installation-Guide#run-infrastructure-and-download-dependencies)

**Comment by noloman** [comment]
Thanks guys, I will give that a try first! Thanks!

**Comment by BerkhanBerkdemir** [comment]
@noloman, did you set up the project with Docker?

**Comment by BerkhanBerkdemir** [comment]
@noloman, I hope that it is working :rofl:. OK. I'm going to reopen this Issue because we need that guide for this project.

**Comment by noloman** [comment]
@BerkhanBerkdemir sorry for the late response, I completely forgot!
Indeed following https://github.com/magara/magara/issues/34#issuecomment-426541007 worked immediately and perfectly 👍

**Comment by BerkhanBerkdemir** [comment]
Thank you for your feedback, @noloman!

I'd like to see a PR from you :blue_heart:

**Comment by mathyoudawson** [comment]
> I'm writing [a Mac OS guide](https://github.com/magara/magara/wiki/Developer-Installation-Guide-for-Mac-OS). However, I'm looking a reviewer for it.
> 
> > When it will be OK, I will add Wiki content index.
> 
> Thank you.

I took a look. I'm sure that rbenv require more configuration, specifically with shims and what not. Might be easier to say that you need 2.5.1 and leave rbenv out of it?

**Comment by noloman** [comment]
I can review it!

Op do 25 okt. 2018 08:28 schreef Matthew Dawson <notifications@github.com>:

**Comment by BerkhanBerkdemir** [comment]
Thanks @mathyoudawson and @noloman :heart:

> I took a look. I'm sure that rbenv require more configuration, specifically with shims and what not. Might be easier to say that you need 2.5.1 and leave rbenv out of it?

Well, I didn't use `rbenv` either :rofl:

---

Also, if you find any typo or grammar, feel free to fix :smile:
