### ISSUE TITLE
Address storing and validation

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#44]
In Issue #36 covers the problem about zip code validation and #37 fixes the problem (thanks to @mathyoudawson). This Issue will be more complicated than #36.

It needs to validate addresses, cities, states even apartment numbers. Moreover, we need to find a way to store address information, so I found a gem that is called [Geocoder](http://www.rubygeocoder.com).

> Furthermore, Ryan's RailsCasts shows how to use Geocoder Gem on episode [273](http://railscasts.com/episodes/273-geocoder).

> [gmaps.js](https://hpneo.github.io/gmaps) provides easy Google Map integration with some cool features which we will use some of them ([Street view panoramas](https://hpneo.github.io/gmaps/examples/streetview.html) and [Markers](https://hpneo.github.io/gmaps/examples/markers.html)).

> [Leafletjs](https://leafletjs.com/) is an alternative of gmap.js for OpenStreetMap.

Also, Issue #17 should look at this Issue because Geocoder resolves that Issue with [OpenStreetMap Nomination](https://nominatim.openstreetmap.org/). For example, [the result of Santa Monica](https://nominatim.openstreetmap.org/details.php?place_id=198798295).

**Comment by noloman** [comment]
hey @BerkhanBerkdemir I'm not really sure what should exactly be done here, could you please clarify it?

**Comment by BerkhanBerkdemir** [comment]
Well, I'm not sure about finding address with zip code, but I'm pretty sure that we can find zip code with address. We need additional apartment/door number for it, @noloman.

Today, I'm going to write a PR, and we can discuss that with some code. Is it cool, @noloman?

**Comment by noloman** [comment]
Sure thing, let me know when that PR is written!

Op di 6 nov. 2018 20:47 schreef Berkhan Berkdemir <notifications@github.com
