### ISSUE TITLE
Fixing coding style for Houses

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#49]
Hey @hoangvq288,

Your work on PR #33 was awesome. I just wanted you to remember it. The PR was about fixing coding style for `HousesHelper.rb` and `HousesController.rb`.

> Also, I'm looking a contributor who can get rid off linter warnings.

**Comment by yhalapup** [comment]
@BerkhanBerkdemir I can try to fix linter warnings in HousesHelper.rb and HousesController.rb

**Comment by BerkhanBerkdemir** [comment]
Hi @yhalapup,

Thank you for your comment. Please read our contribution guide before writing a patch.
