### ISSUE TITLE
Under the .github folder has some issues about grammar

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#50]
Hey @chiku0112,

You worked on PR #48, and it was a good catch; however, the problem was that you didn't follow our [Contribution](https://github.com/magara/magara/blob/master/.github/CONTRIBUTING.md) standard.

## To do list

> :bulb: if anybody finds a grammar mistake, please add a comment.

### Needs fix

- [ ] [`.github/ISSUE_TEMPLATE/BUG_REPORT.md`](https://github.com/magara/magara/blob/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md)

**Comment by iennae** [comment]
This seems like the spelling depends on where folks are located. American english spells without the u.

**Comment by BerkhanBerkdemir** [comment]
I didn't know that until now :flushed:

> Behavior is the preferred spelling in American English. Behaviour is preferred everywhere else. Other than the spelling, there is no difference between the two words.
> &mdash; [grammarist.com](http://grammarist.com/spelling/behavior-behaviour)

Thank you, @iennae!
