### ISSUE TITLE
Removing user account returns a 500 error

### ISSUE THREAD

**Issue by noloman** [magara/magara#55]
https://github.com/magara/magara/projects/1#card-13726863

## Expected Behavior
It should redirect to a account deletion confirmation screen, with a notice message.

<img width="1142" alt="screenshot 2018-11-01 at 08 45 05" src="https://user-images.githubusercontent.com/183264/47839291-87610600-ddb2-11e8-91b2-28cc4d0a6f5e.png">

## Current Behavior
The app now redirects to a 500 error page

## Possible Solution
Making sure that whenever a user is deleted, the houses associated to that user are also deleted.

## Steps to Reproduce (for bugs)
1. Log in
2. Create a house.
3. Remove your account.

**Comment by noloman** [comment]
I'll work on this one if that's OK!

**Comment by BerkhanBerkdemir** [comment]
Thanks, @noloman.

Actually, I forgot to create an Issue about that :cry:

It happens only on production stage, and the 500 was not returned on development stage.

**Comment by noloman** [comment]
Really? I can easily reproduce it in development. What's the production URL by the way?

**Comment by BerkhanBerkdemir** [comment]
Hmm, I just created an user, and I wanted to delete it, but I didn't because it returned 500. I need to check logs, but Heroku just shows a few of them.

**Comment by noloman** [comment]
Did you create a house first? Because the problem is that if you have a
user and a house and remove the user, there’s no `dependent :destroy` or
anything like that in the user model, and that’s why it throws the 500

**Comment by noloman** [comment]
Perfect, I'd also like to improve my RSpec skills. What's the production
URL BTW?

Op za 3 nov. 2018 06:00 schreef Berkhan Berkdemir <notifications@github.com

**Comment by BerkhanBerkdemir** [comment]
Just use staging one. It is same with production. You will find that link on project homepage, @noloman.
