### ISSUE TITLE
Handling money columns, rent & deposit

### ISSUE THREAD

**Issue by AgonIdrizi** [magara/magara#59]
## Current Behavior
Currently we have rent & deposit inputs in `/houses/new` ,accepting integer, but in our schema we have declared them as `t.money`, which is not a good approach.  
When trying to submit a new house I get an error `PG::InvalidTextRepresentation: ERROR: invalid input syntax for type money`

## Possible Solution
One solution is to use this: https://github.com/tobi/money_column

Second solution:
Common practice for handling currency is to use decimal type. Here is a simple example from "Agile Web Development with Rails"

`add_column :products, :price, :decimal, :precision => 8, :scale => 2 `

This will allow you to handle prices from -999,999.99 to 999,999.99
You may also want to include a validation in your items like

```ruby
def validate 
  errors.add(:price, "should be at least 0.01") if price.nil? || price < 0.01 
end
```

to sanity-check your values.

I can do this if allowed.

Thanks,
Agon.

**Comment by BerkhanBerkdemir** [comment]
Hmm, we use PostgreSQL by default, and it comes with [`money`](https://www.postgresql.org/docs/9.1/datatype-money.html#DATATYPE-MONEY) datatype. However, I need to add that I'm not PostgreSQL expert nor banker, so I need to search, but thanks for catching that error :blue_heart:

> Protip: could you use ` when you insert a piece of code

**Comment by noloman** [comment]
I agree with the solution from the Agile Web Development with Rails"
`add_column :products, :price, :decimal, :precision => 8, :scale => 2`
I'm implementing the elasticsearch functionality for the houses and whenever we pass parameters for `rent` and `deposit`, it does not work
