### ISSUE TITLE
Current ad status of houses

### ISSUE THREAD

**Issue by BerkhanBerkdemir** [magara/magara#93]
People want to see active ads instead of 30 years old an ad without any update, so we should add a feature that shows the status of house (ad).

## Implementation

In the model of House (`House.rb`) will have:

```ruby
class House < ApplicationRecord
  # ...
  enum status: { active: 'active', archived: 'archived' }
  # ...
end
```
1. Should use `string` instead of `integer` because `integer` makes hard to understand the context
2. Solve the data integrity issue with database specific `ENUM()` data types.

*P.S. Thanks to Eduardo Figarola's article (link in the sources section)*

## Rails, PostgreSQL and `ENUM()`

<details>
  <summary>An example of migration file</summary>

  ```ruby
  class AddStatusToHouses < ActiveRecord::Migration[5.2]
    def up
      execute <<-SQL
        CREATE TYPE house_statuses AS ENUM ('active', 'archived');
      SQL

      add_column :houses, :status, :house_statuses
    end

    def down
      remove_column :houses, :status, :house_statuses

      execute <<-SQL
        DROP TYPE house_statuses;
      SQL
    end
  end
  ```
</details>

Using this migration file causes to return an exception in the `schema.rb`

```ruby
# ...
# Could not dump table "houses" because of following StandardError
#   Unknown type 'house_statuses' for column 'status'
# ...
```

### Source about Rails, PostgreSQL and `ENUM()`

I read different sources

* [Enums with Rails & ActiveRecord: an improved way](https://sipsandbits.com/2018/04/30/using-database-native-enums-with-rails/)
* [Postgres enums with Rails](https://dev.to/amplifr/postgres-enums-with-rails-4ld0)
* [Enumerated Types with ActiveRecord and PostgreSQL](https://www.sitepoint.com/enumerated-types-with-activerecord-and-postgresql/)

**Comment by memoht** [comment]
`class AddStatusToHouses < ActiveRecord::Migration[5.2]
  def up
    execute <<-SQL
        ALTER TABLE houses ADD status enum('active', 'archived');
    SQL
  end

  def down
    remove_column :houses, :status
  end
end`

**Comment by BerkhanBerkdemir** [comment]
> @BerkhanBerkdemir My interpretation of this [article](https://sipsandbits.com/2018/04/30/using-database-native-enums-with-rails/) and your failed migration would be something like:
> 
> ```ruby
> class AddStatusToHouses < ActiveRecord::Migration[5.2]
>   def up
>     execute <<-SQL
>         ALTER TABLE houses ADD status enum('active', 'archived');
>     SQL
>   end
> 
>   def down
>     remove_column :houses, :status
>   end
> end
> ```

I will check it out. Thank you!

**Comment by BerkhanBerkdemir** [comment]
I also want to add that we discussed this topic on Slack a channel with @memoht. If we want to use PostgreSQL specific function (`ENUM()`), we **have to** use `structure.sql` instead of `schema.rb` since ActiveRecord migration does not know PostgreSQL specific `ENUM()` function.
